volumes:
  db:
services:
  faco-times:
    container_name: faco-times
    image: faco-times:1.0.0
    depends_on:
      - postgres
    build:
      context: .
      target: development
    command:
      - sh
      - -c
      - |
        npm install
        ${START_COMMAND}
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - .:/opt/faco-times/app
      - ./package.json:/opt/faco-times/package.json
      - ./package-lock.json:/opt/faco-times/package-lock.json
    restart: unless-stopped
    extra_hosts:
      - 'faco-times.dev:172.17.0.1'
  postgres:
    container_name: postgres
    image: postgres:11.13
    restart: unless-stopped
    networks:
      - default
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - .docker/init.sh:/docker-entrypoint-initdb.d/init.sh:z
networks:
  default:
    external:
      name: dev-network
